### ISSUE TITLE
Would you add some examples?

### ISSUE THREAD

**Issue by wwhai** [sile/erl-rtmpmsg#5]
# I want to use this lib to push rtmp stream ,but there is no example,I hope you can add some example.

**Comment by sile** [comment]
Thanks for reaching out. 
The aim of this library is to provide the encoding/decoding feature of RTMP messages, so publishing streams to an RTMP server is out of the scope, and I think it's too complex to provide as an example script.
(Please see https://github.com/sile/erl-rtmpmsg#examples for the usage of this library itself)

I once developed a library to publish (and subscribe) RTMP streams based on this library. But, unfortunately, since it's an in-house product, I cannot share the code with you.
